services:
  db:
    image: postgres:16-alpine
    container_name: comunicados_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: comunicados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: